// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgb_xZHcVRDrJ94e0wZc6NL6p8Ww927cs',
    appId: '1:1006532950690:web:451028db69bd1ad46875fb',
    messagingSenderId: '1006532950690',
    projectId: 'palette-9bfd4',
    authDomain: 'palette-9bfd4.firebaseapp.com',
    storageBucket: 'palette-9bfd4.firebasestorage.app',
    measurementId: 'G-RVZPQHBT51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN5BRMsPBpvjksBGtv845T0L-PrAFF94k',
    appId: '1:1006532950690:android:3179270dac38e9a66875fb',
    messagingSenderId: '1006532950690',
    projectId: 'palette-9bfd4',
    storageBucket: 'palette-9bfd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrF85zf8pmIM3Bikrkl1C0qPUp9XKckRM',
    appId: '1:1006532950690:ios:92e25548851f8c716875fb',
    messagingSenderId: '1006532950690',
    projectId: 'palette-9bfd4',
    storageBucket: 'palette-9bfd4.firebasestorage.app',
    iosBundleId: 'com.example.textualPainter',
  );

}